###
Get http://localhost:5000/admin/get-users-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAzOTM1ZTRiY2RkZWM0NTIxODdjNzYiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzMzM4ODMsImV4cCI6MTc0NTMzNzQ4M30.XYuxByujOUZ-UWoZic-h9pCX5pc8C1KUDFmBKCUk9EY

###
Get http://localhost:5000/admin/get-transactions-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAzOTM1ZTRiY2RkZWM0NTIxODdjNzYiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzMzM4ODMsImV4cCI6MTc0NTMzNzQ4M30.XYuxByujOUZ-UWoZic-h9pCX5pc8C1KUDFmBKCUk9EY

###
Get http://localhost:5000/admin/get-revenue-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAzOTM1ZTRiY2RkZWM0NTIxODdjNzYiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzMzM4ODMsImV4cCI6MTc0NTMzNzQ4M30.XYuxByujOUZ-UWoZic-h9pCX5pc8C1KUDFmBKCUk9EY

###
Get http://localhost:5000/admin/get-balance HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAzOTM1ZTRiY2RkZWM0NTIxODdjNzYiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzMzM4ODMsImV4cCI6MTc0NTMzNzQ4M30.XYuxByujOUZ-UWoZic-h9pCX5pc8C1KUDFmBKCUk9EY

###
Get http://localhost:5000/admin/last-transactions HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODAzOTM1ZTRiY2RkZWM0NTIxODdjNzYiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzMzM4ODMsImV4cCI6MTc0NTMzNzQ4M30.XYuxByujOUZ-UWoZic-h9pCX5pc8C1KUDFmBKCUk9EY
