###
Get http://localhost:5000/admin/get-users-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzOTU3NzksImV4cCI6MTc0NTM5OTM3OX0.tS7sOiUZiqK3LtZs6WogReVsS39FksqGVAQekVymjUk

###
Get http://localhost:5000/admin/get-transactions-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzOTU3NzksImV4cCI6MTc0NTM5OTM3OX0.tS7sOiUZiqK3LtZs6WogReVsS39FksqGVAQekVymjUk

###
Get http://localhost:5000/admin/get-revenue-total HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzOTU3NzksImV4cCI6MTc0NTM5OTM3OX0.tS7sOiUZiqK3LtZs6WogReVsS39FksqGVAQekVymjUk

###
Get http://localhost:5000/admin/get-balance HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzOTU3NzksImV4cCI6MTc0NTM5OTM3OX0.tS7sOiUZiqK3LtZs6WogReVsS39FksqGVAQekVymjUk

###
Get http://localhost:5000/admin/last-transactions HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzOTU3NzksImV4cCI6MTc0NTM5OTM3OX0.tS7sOiUZiqK3LtZs6WogReVsS39FksqGVAQekVymjUk

###
Get http://localhost:5000/admin/get-hotel-count HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODA0NjM1Y2FjNWUzYzRmNjZkODkzYzUiLCJ1c2VyTmFtZSI6ImFkbWluQGdtYWlsLmNvbSIsImZ1bGxOYW1lIjoiIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NDUzOTU3NzksImV4cCI6MTc0NTM5OTM3OX0.tS7sOiUZiqK3LtZs6WogReVsS39FksqGVAQekVymjUk
